# Generated by Django 3.2.12 on 2022-02-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('activity_id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('activity_date', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=3, max_digits=8)),
                ('polyline', models.CharField(max_length=512)),
                ('exercise_type', models.CharField(max_length=2)),
                ('moving_time', models.IntegerField()),
                ('elapsed_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('brief_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('muscle_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('insertion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320)),
                ('fname', models.CharField(max_length=35)),
                ('sname', models.CharField(max_length=35)),
                ('hashedPassword', models.CharField(max_length=64)),
                ('uniqueSalt', models.BinaryField(max_length=32)),
                ('stravaAuthorised', models.BooleanField(default=False)),
                ('stravaAccessToken', models.CharField(default='', max_length=40)),
                ('stravaRefreshToken', models.CharField(default='', max_length=40)),
                ('stravaAccessTokenExpiresAt', models.IntegerField(null=True)),
                ('verifiedViaEmail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('workout_plan_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('days_of_the_week', models.CharField(max_length=7)),
                ('workout_plan_name', models.CharField(max_length=30)),
                ('workout_streak', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=30)),
                ('workout_date', models.DateTimeField()),
                ('workout_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('pb_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.exercise')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleWorked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.exercise')),
                ('muscle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.exercise')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.activitydetail')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
