# Generated by Django 4.0.2 on 2022-02-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_id',
            new_name='activity',
        ),
    ]
