# Generated by Django 4.0.2 on 2022-03-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityDetail',
        ),
    ]
