# Generated by Django 4.0.2 on 2022-03-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_activitydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('activity_id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('activity_date', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=3, max_digits=8)),
                ('polyline', models.CharField(max_length=4096)),
                ('exercise_type', models.CharField(max_length=5)),
                ('moving_time', models.IntegerField()),
                ('elapsed_time', models.IntegerField()),
                ('activity_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.activitydetail')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
