# Generated by Django 3.2.12 on 2022-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_activitydetail_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_plan_id',
            new_name='workout_plan',
        ),
        migrations.AddField(
            model_name='user',
            name='currentWorkoutPlanActive',
            field=models.CharField(default='', max_length=80),
        ),
    ]
