# Generated by Django 3.2.12 on 2022-03-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220305_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_date',
        ),
    ]
