# Generated by Django 3.2.12 on 2022-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_workout_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='workout_streak',
        ),
    ]
