# Generated by Django 3.2.12 on 2022-03-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_workoutplan_workout_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_name',
        ),
    ]
